# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-15 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('authors', models.ManyToManyField(to='db.Author')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Blog')),
            ],
        ),
    ]
