# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-16 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
